/**
 * This file was automatically generated by VersionTag.cmake
 */
#pragma once
#define pow_VERSION_MAJOR			0
#define pow_VERSION_MINOR			0
#define pow_VERSION_PATCH			0
#define pow_VERSION_EXTRA			

// Current pow version number as a string.
#define pow_VERSION				"0.0.0"

// Current pow extended version number as a string.
#define pow_VERSION_EXTENDED		"0.0.0"
